name: Linting

on:
  push:
    branches:
      - master
      - develop

  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install
      run: |
        python -m pip install -U pip
        python -m pip install -U black
        python -m pip install -U flake8
        python -m pip install -U isort
        python -m pip install -U mypy
        pip install --progress-bar off -U .[checking]
    - name: black
      run: black . --check --diff
    - name: flake8
      run: flake8 .
    - name: mypy
      run: mypy
